export {Header} from './Header/Header'
export {MainContent} from './MainContent/MainContent'
export {Footer} from './Footer/Footer'
export {MovieList} from './MovieList/MovieList'
export {ErrorBoundary} from './ErrorBoundary/ErrorBoundary'